# Generated by Django 2.2.4 on 2023-01-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pypie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypie',
            name='users_who_votes',
            field=models.ManyToManyField(related_name='liked_pie', to='Pypie_app.User'),
        ),
    ]
