# Generated by Django 2.2.4 on 2023-01-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pypie_app', '0002_pypie_users_who_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pypie',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
